### PR TITLE
Add articles from www.ft.com to user-history data

### PR DESCRIPTION
**Pull request by phamann**
This adds old article paths such as `/cms/s/0/06e3043a-198c-11e5-8201-cbdb03d71480.html` from `www.ft.com` events to be added to the user-history database.

Was much easier that I thought, should have done ages ago...

/cc @adgad @commuterjoy

### CODE REVIEW

**Comment by adgad** [comment]
:+1: nice!

**Comment by commuterjoy** [comment]
note it will not catch things like blogs and fastft articles (which in next have guids, but in ft.com have friendly names)

**Comment by matthew-andrews** [comment]
@commuterjoy 
^^ mike h of hui fame just had a chat with me about the same problem.  i was wondering whether Sarah Wells' new concordance API could support mapping between old Fast FT & WordPress identifiers to solve this problem here, the same problem in HUI and we will have this problem when it comes to redirection of WordPress articles into Next………

**Comment by commuterjoy** [comment]
that would be really nice

**Comment by phamann** [comment]
@commuterjoy Yep, very aware of this. Short term answer: we don't care...

**Comment by sjwells** [comment]
@matthew-andrews Concordance API wouldn't be the right place (it's very specifically about annotations, not content). However, we do know original identifiers for blogs and FastFT, and could for example allow content or enriched content lookups using a combination of authority and identifier value, like with annotations.

**Pull request merged**
