### PR TITLE
Fix stream tag meta

### PR DESCRIPTION
**Pull request by phamann**
Refactors the `getStreamTagContent` method to increase its success rate, now uses 10 articles from search to filter and find the tag meta data.

/cc @adgad @matthew-andrews

### CODE REVIEW

**Comment by matthew-andrews** [comment]
hack hack hack :+1:

**Comment by matthew-andrews** [comment]
you might also want

**Comment by matthew-andrews** [comment]
https://github.com/Financial-Times/next-dobi/blob/master/server/lib/flatten-metadata.js

**Comment by matthew-andrews** [comment]
actually that might explain more of the failures than the retry……

**Comment by matthew-andrews** [comment]
basically `tags` doesn't contain all an article's tags…… you have to munge it all together :disappointed:

**Comment by phamann** [comment]
@matthew-andrews Cheers, and yes that definitely explains a lot! Let's hope this does the trick :smile:

**Comment by phamann** [comment]
@matthew-andrews Cheers, and yes that definitely explains a lot! Let's hope this does the trick :smile:

**Pull request merged**
